LiveMap Class Reference
This class manages live map creation in `live mode`, by dynamically updating the map from incoming ROS data (e.g., from RosHandler). It builds an occupancy grid in real time and draws it using a ViewController.
#include <LiveMap.hpp>
Public Member Functions
LiveMap (int size, double resolution, ViewController &controller)
Constructor: initializes map size, resolution and controller reference.
void addPoint (double x, double y)
Adds a single point (in real-world coordinates) to the internal point buffer.
void setPoints (const std::vector< double > &newX, const std::vector< double > &newY)
Replaces current point buffer with a new set of coordinates.
void clearPoints ()
Clears all stored real-world points.
void clearGrid ()
Clears the occupancy grid (sets all cells to 0)
void xy2Grid (const std::vector< double > &x, const std::vector< double > &y, std::vector< int > &xGrid, std::vector< int > &yGrid)
Converts real-world coordinates to grid indices.
void fillGrid (const std::vector< int > &xGrid, const std::vector< int > &yGrid)
Fills the grid using the given grid indices, marking cells as occupied (1)
const std::vector< std::vector< int > > & getGrid () const
Returns a constant reference to the full occupancy grid.
void updateGridFromPoints ()
Updates the grid from the internal point buffer.
void drawLiveMap (sf::RenderTarget &target) const
Draws the live grid using the ViewController.
void setActive (bool isActive)
Activates or deactivates live mode (when true, dynamic updates occur)
bool getIsActive () const
Returns whether live mode is currently active.
void setStart (int i, int j)
Sets a special start cell in the grid (value = 's')
void setGoal (int i, int j)
Sets a special goal cell in the grid (value = 'g')
const std::vector< double > & getRealX () const
Getters for real-world x coordinates.
const std::vector< double > & getRealY () const
Getters for real-world y coordinates.
Private Attributes
ViewController & controller
Reference to the view controller for rendering.
int gridSize
Map size (number of cells per side)
double gridResolution
Size of each cell in real-world units.
std::vector< double > posX
std::vector< double > posY
Buffer of real-world x/y points.
std::vector< std::vector< int > > grid
2D occupancy grid (0 = free, 1 = occupied, 's' = start, 'g' = goal)
bool originSet = false
Flag to know if the origin is initialized.
double originX = 0.0
double originY = 0.0
Optional offset for positioning.
bool isLivemodeActive = false
Whether live updates are happening.
Detailed Description
This class manages live map creation in `live mode`, by dynamically updating the map from incoming ROS data (e.g., from RosHandler). It builds an occupancy grid in real time and draws it using a ViewController.
Definition at line 27 of file LiveMap.hpp.
Constructor & Destructor Documentation
LiveMap()
LiveMap::LiveMap (int size, double resolution, ViewController & controller)
Constructor: initializes map size, resolution and controller reference.
Constructs a LiveMap object with specified grid size and resolution.
Parameters
size Number of grid cells per side
resolution Size of each grid cell in meters
controller Reference to the view controller
Initializes the occupancy grid and links to the ViewController.
Parameters
size Number of grid cells per side (square grid).
resolution Cell size in meters.
controller Reference to ViewController for visualization parameters.
Definition at line 25 of file LiveMap.cpp.
    : gridSize(size), gridResolution(resolution), controller(controller), originSet(false)
{
    // Initialize grid to all free cells (0)
    grid.resize(gridSize, std::vector<int>(gridSize, 0));
    // Clear stored real-world points
    posX.clear();
    posY.clear();
}
References grid, gridSize, posX, and posY.
Member Function Documentation
addPoint()
void LiveMap::addPoint (double x, double y)
Adds a single point (in real-world coordinates) to the internal point buffer.
Adds a new real-world point to the list.
Parameters
x Real-world X coordinate
y Real-world Y coordinate
The first point added is used to set the origin for coordinate conversion.
Parameters
x X coordinate in meters.
y Y coordinate in meters.
Definition at line 42 of file LiveMap.cpp.
{
    if (!originSet) {
        originX = x;
        originY = y;
        originSet = true;
    }
    posX.push_back(x);
    posY.push_back(y);
}
References originSet, originX, originY, posX, and posY.
Referenced by MapViewer::update().
clearGrid()
void LiveMap::clearGrid ()
Clears the occupancy grid (sets all cells to 0)
Resets the occupancy grid cells to free (0).
Definition at line 77 of file LiveMap.cpp.
{
    for (auto& row : grid) {
        std::fill(row.begin(), row.end(), 0);
    }
}
References grid.
Referenced by fillGrid(), and MapViewer::update().
clearPoints()
void LiveMap::clearPoints ()
Clears all stored real-world points.
Clears all stored real-world points and resets the origin flag.
Definition at line 67 of file LiveMap.cpp.
{
    posX.clear();
    posY.clear();
    originSet = false;
}
References originSet, posX, and posY.
Referenced by MapViewer::update().
drawLiveMap()
void LiveMap::drawLiveMap (sf::RenderTarget & target) const
Draws the live grid using the ViewController.
Draws occupied cells of the live map on the given SFML render target.
Parameters
target SFML render target
The drawing is centered and scaled according to the controller parameters.
Parameters
target SFML RenderTarget to draw on.
Definition at line 155 of file LiveMap.cpp.
{
    if (grid.empty()) return;
    float metersPerCell = controller.getMetersPerCell(); // e.g., 0.1
    float pixelsPerMeter = controller.getPixelsPerMeter(); // e.g., 50.0
    float cellSize = metersPerCell * pixelsPerMeter;
    int rows = static_cast<int>(grid.size());
    int cols = static_cast<int>(grid[0].size());
    int halfCols = cols / 2;
    int halfRows = rows / 2;
    float zoom = controller.getZoom();
    sf::RectangleShape cellShape;
    cellShape.setFillColor(sf::Color::Magenta);
    cellShape.setSize(sf::Vector2f(cellSize / zoom, cellSize / zoom));
    for (int row = 0; row < rows; ++row) {
        for (int col = 0; col < cols; ++col) {
            if (grid[row][col] == 1) {
                int cellX = col - halfCols;
                int cellY = row - halfRows;
                float x = static_cast<float>(cellX) * cellSize / zoom;
                float y = static_cast<float>(cellY) * cellSize / zoom;
                cellShape.setPosition(x, y);
                target.draw(cellShape);
            }
        }
    }
}
References controller, ViewController::getMetersPerCell(), ViewController::getPixelsPerMeter(), ViewController::getZoom(), and grid.
Referenced by MapViewer::render().
fillGrid()
void LiveMap::fillGrid (const std::vector< int > & xGrid, const std::vector< int > & yGrid)
Fills the grid using the given grid indices, marking cells as occupied (1)
Fills the grid with obstacles at specified grid indices.
Parameters
xGrid Vector of X grid indices
yGrid Vector of Y grid indices
Previous occupancy data is cleared.
Parameters
xGrid Vector of X grid indices.
yGrid Vector of Y grid indices.
Definition at line 124 of file LiveMap.cpp.
{
    if (xGrid.size() != yGrid.size()) return;
    clearGrid();
    for (size_t i = 0; i < xGrid.size(); ++i) {
        int xIdx = xGrid[i];
        int yIdx = yGrid[i];
        grid[yIdx][xIdx] = 1; // Mark cell as occupied
    }
}
References clearGrid(), and grid.
Referenced by updateGridFromPoints().
getGrid()
const std::vector<std::vector<int> >& LiveMap::getGrid () const [inline]
Returns a constant reference to the full occupancy grid.
Returns
Constant reference to grid
Definition at line 82 of file LiveMap.hpp.
{ return grid; };
References grid.
Referenced by MapViewer::render().
getIsActive()
bool LiveMap::getIsActive () const [inline]
Returns whether live mode is currently active.
Returns
True if live mode is active
Definition at line 105 of file LiveMap.hpp.
{ return isLivemodeActive; };
References isLivemodeActive.
Referenced by RightClickMapMenu::connectSignals(), and FileManager::saveDialog().
getRealX()
const std::vector<double>& LiveMap::getRealX () const [inline]
Getters for real-world x coordinates.
Returns
Vector of x coordinates
Definition at line 125 of file LiveMap.hpp.
{ return posX; }
References posX.
Referenced by FileManager::saveDialog().
getRealY()
const std::vector<double>& LiveMap::getRealY () const [inline]
Getters for real-world y coordinates.
Returns
Vector of y coordinates
Definition at line 131 of file LiveMap.hpp.
{ return posY; }
References posY.
Referenced by FileManager::saveDialog().
setActive()
void LiveMap::setActive (bool isActive) [inline]
Activates or deactivates live mode (when true, dynamic updates occur)
Parameters
isActive True to activate, false to deactivate
Definition at line 99 of file LiveMap.hpp.
{ isLivemodeActive = true; };
References isLivemodeActive.
setGoal()
void LiveMap::setGoal (int i, int j)
Sets a special goal cell in the grid (value = 'g')
Marks a cell as the goal in the grid using ASCII code 'g' (103).
Parameters
i Grid row index
j Grid column index
i Row index.
j Column index.
Definition at line 197 of file LiveMap.cpp.
{
    grid[i][j] = 103; // ASCII 'g'
}
References grid.
Referenced by RightClickMapMenu::connectSignals().
setPoints()
void LiveMap::setPoints (const std::vector< double > & newX, const std::vector< double > & newY)
Replaces current point buffer with a new set of coordinates.
Replaces stored points with a new set.
Parameters
newX New set of X coordinates
newY New set of Y coordinates
newX Vector of X coordinates.
newY Vector of Y coordinates.
Definition at line 58 of file LiveMap.cpp.
{
    posX = newX;
    posY = newY;
}
References posX, and posY.
setStart()
void LiveMap::setStart (int i, int j)
Sets a special start cell in the grid (value = 's')
Marks a cell as the start in the grid using ASCII code 's' (115).
Parameters
i Grid row index
j Grid column index
i Row index.
j Column index.
Definition at line 207 of file LiveMap.cpp.
{
    grid[i][j] = 115; // ASCII 's'
}
References grid.
updateGridFromPoints()
void LiveMap::updateGridFromPoints ()
Updates the grid from the internal point buffer.
Updates the occupancy grid based on the stored real-world points.
Definition at line 141 of file LiveMap.cpp.
{
    if (posX.empty() || posY.empty()) return;
    std::vector<int> xGrid, yGrid;
    xy2Grid(posX, posY, xGrid, yGrid);
    fillGrid(xGrid, yGrid);
}
References fillGrid(), posX, posY, and xy2Grid().
Referenced by MapViewer::update().
xy2Grid()
void LiveMap::xy2Grid (const std::vector< double > & x, const std::vector< double > & y, std::vector< int > & xGrid, std::vector< int > & yGrid)
Converts real-world coordinates to grid indices.
Converts real-world coordinates to grid indices relative to the origin.
Parameters
x Vector of real-world X coordinates
y Vector of real-world Y coordinates
xGrid Output vector for grid X indices
yGrid Output vector for grid Y indices
Points outside the grid are ignored.
Parameters
x Vector of X coordinates.
y Vector of Y coordinates.
xGrid Output vector of grid X indices.
yGrid Output vector of grid Y indices.
Definition at line 92 of file LiveMap.cpp.
{
    if (x.size() != y.size() || !originSet) return;
    xGrid.clear();
    yGrid.clear();
    int halfGrid = gridSize / 2;
    for (size_t i = 0; i < x.size(); ++i) {
        double shiftedX = x[i] - originX;
        double shiftedY = y[i] - originY;
        int xIdx = static_cast<int>(std::round(shiftedX / gridResolution)) + halfGrid;
        int yIdx = static_cast<int>(std::round(shiftedY / gridResolution)) + halfGrid;
        // Ignore points outside grid bounds
        if (xIdx < 0 || xIdx >= gridSize || yIdx < 0 || yIdx >= gridSize)
            continue;
        xGrid.push_back(xIdx);
        yGrid.push_back(yIdx);
    }
}
References gridResolution, gridSize, originSet, originX, and originY.
Referenced by updateGridFromPoints().
Member Data Documentation
controller
ViewController& LiveMap::controller [private]
Reference to the view controller for rendering.
Definition at line 134 of file LiveMap.hpp.
Referenced by drawLiveMap().
grid
std::vector<std::vector<int> > LiveMap::grid [private]
2D occupancy grid (0 = free, 1 = occupied, 's' = start, 'g' = goal)
Definition at line 139 of file LiveMap.hpp.
Referenced by clearGrid(), drawLiveMap(), fillGrid(), getGrid(), LiveMap(), setGoal(), and setStart().
gridResolution
double LiveMap::gridResolution [private]
Size of each cell in real-world units.
Definition at line 136 of file LiveMap.hpp.
Referenced by xy2Grid().
gridSize
int LiveMap::gridSize [private]
Map size (number of cells per side)
Definition at line 135 of file LiveMap.hpp.
Referenced by LiveMap(), and xy2Grid().
isLivemodeActive
bool LiveMap::isLivemodeActive = false [private]
Whether live updates are happening.
Definition at line 144 of file LiveMap.hpp.
Referenced by getIsActive(), and setActive().
originSet
bool LiveMap::originSet = false [private]
Flag to know if the origin is initialized.
Definition at line 141 of file LiveMap.hpp.
Referenced by addPoint(), clearPoints(), and xy2Grid().
originX
double LiveMap::originX = 0.0 [private]
Definition at line 142 of file LiveMap.hpp.
Referenced by addPoint(), and xy2Grid().
originY
double LiveMap::originY = 0.0 [private]
Optional offset for positioning.
Definition at line 142 of file LiveMap.hpp.
Referenced by addPoint(), and xy2Grid().
posX
std::vector<double> LiveMap::posX [private]
Definition at line 138 of file LiveMap.hpp.
Referenced by addPoint(), clearPoints(), getRealX(), LiveMap(), setPoints(), and updateGridFromPoints().
posY
std::vector<double> LiveMap::posY [private]
Buffer of real-world x/y points.
Definition at line 138 of file LiveMap.hpp.
Referenced by addPoint(), clearPoints(), getRealY(), LiveMap(), setPoints(), and updateGridFromPoints().
The documentation for this class was generated from the following files:
include/artgslam_vsc/LiveMap.hpp
src/LiveMap.cpp