MapViewer Class Reference
This is the main class. It manages mouse/keyboard events and GUI integration. It also coordinates the rendering and simulation components of the application.
#include <MapViewer.hpp>
Public Member Functions
MapViewer (sf::RenderWindow &win)
Constructor.
void update ()
Manages logic updates and user interaction.
void processEvent ()
Handles input events (mouse and keyboard)
void render ()
Renders all visual components to the screen.
bool isRunning () const
Returns whether the viewer should keep running.
Private Attributes
sf::RenderWindow & window
Reference to the SFML window for rendering.
sf::View view
SFML camera view.
tgui::Gui gui
GUI system for handling menus and widgets.
MenuBar menu
Instance of the custom menu bar.
FileManager manager
Manages file loading/saving.
RosHandler roshandler
Handles communication with ROS (publishing/subscribing)
ViewController controller
Manages zoom, panning, grid drawing, and coordinate conversions.
GridMap map
Represents and stores the occupancy grid.
UnicicleWmr wmr
Simulated unicycle WMR (Wheeled Mobile Robot)
LiveMap livemap
Handles live mapping mode based on ROS data.
RightClickMapMenu r_menu
Context menu for selecting start and goal positions.
AStar aStarsim
A* algorithm instance for path planning and animation.
bool running = true
Indicates whether the main loop is running.
sf::Vector2f worldXY
World coordinates (floating point)
sf::Vector2i gridIndex
Current hovered grid cell.
sf::Vector2i gridIndex2copy
Temporary copy of a selected grid index.
bool astarAnimating = false
Indicates whether the A* animation is currently running.
Detailed Description
This is the main class. It manages mouse/keyboard events and GUI integration. It also coordinates the rendering and simulation components of the application.
Definition at line 35 of file MapViewer.hpp.
Constructor & Destructor Documentation
MapViewer()
MapViewer::MapViewer (sf::RenderWindow & win)
Constructor.
Constructs a MapViewer instance.
Parameters
win Reference to the SFML render window
Initializes references to the SFML window, GUI, controller, map, menu, ROS handler, robot model, live map, right-click menu, and A* simulation. Sets up menu callbacks and connects right-click menu signals.
Parameters
win Reference to the SFML RenderWindow where rendering occurs.
< Connect right-click menu event callbacks
< Load map file dialog
< Save map file dialog
< Exit application
< Reset camera view
< Clear the grid map
< Open robot creator tool
< Run A* pathfinding animation
< Update start and goal points
< Start A* animation
Definition at line 29 of file MapViewer.cpp.
    : window(win) // Store reference to SFML window
    , view(window.getDefaultView()) // Initialize default camera view
    , gui(win) // Initialize GUI with window reference
    , controller(win, 0.4f, 50.0f, view) // Initialize ViewController with parameters
    , map(1000, 0.4f, controller) // Initialize GridMap with size, resolution, controller
    , manager(map,livemap) // FileManager with reference to GridMap
    , menu(gui) // MenuBar with GUI reference
    , roshandler() // ROS data handler for sensors and velocity
    , wmr() // Wheeled Mobile Robot model
    , livemap(1000, 0.4f, controller) // LiveMap with same size and resolution
    , r_menu(gui, map, livemap) // Right-click menu with GUI, map, and livemap refs
    , aStarsim(map) // A* pathfinding simulator with GridMap
{
    r_menu.connectSignals(); /**< Connect right-click menu event callbacks */
    // Set callback functions for menu bar actions
    menu.setCallbacks(
        [this]() { manager.loadDialog(); }, /**< Load map file dialog */
        [this]() { manager.saveDialog(); }, /**< Save map file dialog */
        [this]() { /* TODO: Implement image saving functionality */ },
        [this]() { running = false; window.close(); }, /**< Exit application */
        [this]() { controller.reset(); }, /**< Reset camera view */
        [this]() { map.clearGridMap(); }, /**< Clear the grid map */
        [this]() { /**< Open robot creator tool */
            RobotCreator creator(wmr);
            creator.run();
        },
        [this]() { /**< Run A* pathfinding animation */
            aStarsim.updatemap(); /**< Update start and goal points */
            aStarsim.start(); /**< Start A* animation */
            astarAnimating = true;
        }
    );
}
References astarAnimating, aStarsim, GridMap::clearGridMap(), RightClickMapMenu::connectSignals(), controller, FileManager::loadDialog(), manager, map, menu, r_menu, ViewController::reset(), RobotCreator::run(), running, FileManager::saveDialog(), MenuBar::setCallbacks(), AStar::start(), AStar::updatemap(), window, and wmr.
Member Function Documentation
isRunning()
bool MapViewer::isRunning () const
Returns whether the viewer should keep running.
Checks if the MapViewer application is running.
Returns
True if running, false otherwise
true if the application is running and window is open, false otherwise.
Definition at line 232 of file MapViewer.cpp.
{
    return running && window.isOpen();
}
References running, and window.
Referenced by main().
processEvent()
void MapViewer::processEvent ()
Handles input events (mouse and keyboard)
Processes SFML window events.
Handles user inputs including window closing, mouse clicks, and GUI events. Shows or hides the right-click menu on mouse events. < Forward event to GUI system
< Forward event to view controller
< Close window and exit
Definition at line 137 of file MapViewer.cpp.
{
    sf::Event event;
    while (window.pollEvent(event)) {
        gui.handleEvent(event); /**< Forward event to GUI system */
        controller.handleEvent(event); /**< Forward event to view controller */
        if (event.type == sf::Event::Closed) {
            running = false;
            window.close(); /**< Close window and exit */
        }
        if (event.type == sf::Event::MouseButtonPressed) {
            const int gridSize = map.getMapSize();
            const sf::Vector2i cell = controller.getHoveredCell(gridSize);
            const sf::Vector2i pixelPos = sf::Mouse::getPosition(window);
            const sf::Vector2f pixelPosF(pixelPos);
            if (event.mouseButton.button == sf::Mouse::Right) {
                // Show context menu at mouse position for right-click
                r_menu.show(static_cast<float>(pixelPos.x),
                            static_cast<float>(pixelPos.y),
                            cell);
                r_menu.setVisible(true);
            } else if (event.mouseButton.button == sf::Mouse::Left) {
                // Hide menu if click is outside of the menu area
                if (r_menu.isVisible() && !r_menu.containsPoint(pixelPosF)) {
                    r_menu.setVisible(false);
                }
            }
        }
    }
}
References RightClickMapMenu::containsPoint(), controller, ViewController::getHoveredCell(), GridMap::getMapSize(), gui, ViewController::handleEvent(), RightClickMapMenu::isVisible(), map, r_menu, running, RightClickMapMenu::setVisible(), RightClickMapMenu::show(), and window.
Referenced by main().
render()
void MapViewer::render ()
Renders all visual components to the screen.
Renders the entire map viewer frame.
Clears the window, draws the grid and axes, live or stored maps, A* simulation, robot, GUI, and presents the final image. < Clear window with black background
< Apply current camera transform (zoom, pan)
< Draw grid lines
< Draw X and Y axes
< Draw live sensor data map
< Draw stored occupancy grid
Definition at line 177 of file MapViewer.cpp.
{
    window.clear(sf::Color::Black); /**< Clear window with black background */
    controller.applyView(); /**< Apply current camera transform (zoom, pan) */
    controller.drawGrid(window); /**< Draw grid lines */
    controller.drawAxes(window); /**< Draw X and Y axes */
    // Draw live map or stored grid map based on live mode status
    if (menu.getLiveMode()) {
        const auto& gridLive = livemap.getGrid();
        if (gridLive.empty() || gridLive[0].empty()) {
            std::cout << "Live grid is empty!" << std::endl;
            window.setView(window.getDefaultView());
            gui.draw();
            window.display();
            return;
        }
        livemap.drawLiveMap(window); /**< Draw live sensor data map */
    } else {
        const auto& gridMap = map.getGrid();
        if (gridMap.empty() || gridMap[0].empty()) {
            std::cout << "Grid map is empty!" << std::endl;
            window.setView(window.getDefaultView());
            gui.draw();
            window.display();
            return;
        }
        map.draw(window, controller.getPixelsPerMeter()); /**< Draw stored occupancy grid */
    }
    // Draw A* algorithm visualization while animating
    if (astarAnimating) {
        aStarsim.draw(window, 50.0f, controller.getMetersPerCell());
    }
    // Draw the final path found by A* (if any)
    aStarsim.drawFoundPath(window, 50.0f, controller.getMetersPerCell());
    // Draw robot’s current pose and orientation
    wmr.draw(window);
    // Draw GUI elements on top (using default view)
    window.setView(window.getDefaultView());
    gui.draw();
    // Display everything on screen
    window.display();
}
References ViewController::applyView(), astarAnimating, aStarsim, controller, UnicicleWmr::draw(), AStar::draw(), GridMap::draw(), ViewController::drawAxes(), AStar::drawFoundPath(), ViewController::drawGrid(), LiveMap::drawLiveMap(), LiveMap::getGrid(), GridMap::getGrid(), MenuBar::getLiveMode(), ViewController::getMetersPerCell(), ViewController::getPixelsPerMeter(), gui, livemap, map, menu, window, and wmr.
Referenced by main().
update()
void MapViewer::update ()
Manages logic updates and user interaction.
Updates application logic per frame.
Updates mouse position and grid cell info, live mode sensor data, A* animation, and robot model position. < Clear existing sonar points
< Clear live occupancy grid
Definition at line 71 of file MapViewer.cpp.
{
    int gridSize = map.getMapSize();
    // Get the grid cell currently under the mouse cursor
    sf::Vector2i gridIndex = controller.getHoveredCell(gridSize);
    // Get mouse position in world coordinates (meters)
    sf::Vector2f worldPos = controller.getMouseWorldPosition();
    // Prepare coordinate status string with fixed precision
    std::ostringstream oss;
    oss << std::fixed << std::setprecision(2)
        << "Mouse: (" << worldPos.x << ", " << worldPos.y << ") m";
    if (gridIndex.x != -1 && gridIndex.y != -1) {
        oss << " | Grid: (" << gridIndex.x << ", " << gridIndex.y << ")";
    } else {
        oss << " | Out of bounds";
    }
    // Update coordinate display in status bar
    menu.updateCoordinates(oss.str());
    // -------- Live Mode: real-time sensor updates --------
    if (menu.getLiveMode()) {
        livemap.clearPoints(); /**< Clear existing sonar points */
        livemap.clearGrid(); /**< Clear live occupancy grid */
        // Update robot velocity from ROS data
        double v = roshandler.getLinearVelocity();
        double w = roshandler.getAngularVelocity();
        wmr.setVelocity(v, w);
        // Add sonar points to live map
        const auto& sonar = roshandler.getSonarPoints();
        for (const auto& p : sonar) {
            livemap.addPoint(p.x, p.y);
        }
        // Update live map grid with sonar points
        livemap.updateGridFromPoints();
    }
    // -------- A* Animation: step-by-step simulation --------
    if (astarAnimating) {
        if (!aStarsim.isFinished()) {
            bool continueAnim = aStarsim.step();
            if (!continueAnim) {
                astarAnimating = false;
            }
        } else {
            astarAnimating = false;
        }
    }
    // Update robot model position using ROS delta time
    wmr.update(roshandler.getLastDeltaTime());
}
References LiveMap::addPoint(), astarAnimating, aStarsim, LiveMap::clearGrid(), LiveMap::clearPoints(), controller, RosHandler::getAngularVelocity(), ViewController::getHoveredCell(), RosHandler::getLastDeltaTime(), RosHandler::getLinearVelocity(), MenuBar::getLiveMode(), GridMap::getMapSize(), ViewController::getMouseWorldPosition(), RosHandler::getSonarPoints(), gridIndex, AStar::isFinished(), livemap, map, menu, roshandler, UnicicleWmr::setVelocity(), AStar::step(), UnicicleWmr::update(), MenuBar::updateCoordinates(), LiveMap::updateGridFromPoints(), and wmr.
Referenced by main().
Member Data Documentation
astarAnimating
bool MapViewer::astarAnimating = false [private]
Indicates whether the A* animation is currently running.
Definition at line 57 of file MapViewer.hpp.
Referenced by MapViewer(), render(), and update().
aStarsim
AStar MapViewer::aStarsim [private]
A* algorithm instance for path planning and animation.
Definition at line 50 of file MapViewer.hpp.
Referenced by MapViewer(), render(), and update().
controller
ViewController MapViewer::controller [private]
Manages zoom, panning, grid drawing, and coordinate conversions.
Definition at line 45 of file MapViewer.hpp.
Referenced by MapViewer(), processEvent(), render(), and update().
gridIndex
sf::Vector2i MapViewer::gridIndex [private]
Current hovered grid cell.
Definition at line 54 of file MapViewer.hpp.
Referenced by update().
gridIndex2copy
sf::Vector2i MapViewer::gridIndex2copy [private]
Temporary copy of a selected grid index.
Definition at line 55 of file MapViewer.hpp.
gui
tgui::Gui MapViewer::gui [private]
GUI system for handling menus and widgets.
Definition at line 40 of file MapViewer.hpp.
Referenced by processEvent(), and render().
livemap
LiveMap MapViewer::livemap [private]
Handles live mapping mode based on ROS data.
Definition at line 48 of file MapViewer.hpp.
Referenced by render(), and update().
manager
FileManager MapViewer::manager [private]
Manages file loading/saving.
Definition at line 43 of file MapViewer.hpp.
Referenced by MapViewer().
map
GridMap MapViewer::map [private]
Represents and stores the occupancy grid.
Definition at line 46 of file MapViewer.hpp.
Referenced by MapViewer(), processEvent(), render(), and update().
menu
MenuBar MapViewer::menu [private]
Instance of the custom menu bar.
Definition at line 42 of file MapViewer.hpp.
Referenced by MapViewer(), render(), and update().
r_menu
RightClickMapMenu MapViewer::r_menu [private]
Context menu for selecting start and goal positions.
Definition at line 49 of file MapViewer.hpp.
Referenced by MapViewer(), and processEvent().
roshandler
RosHandler MapViewer::roshandler [private]
Handles communication with ROS (publishing/subscribing)
Definition at line 44 of file MapViewer.hpp.
Referenced by update().
running
bool MapViewer::running = true [private]
Indicates whether the main loop is running.
Definition at line 52 of file MapViewer.hpp.
Referenced by isRunning(), MapViewer(), and processEvent().
view
sf::View MapViewer::view [private]
SFML camera view.
Definition at line 39 of file MapViewer.hpp.
window
sf::RenderWindow& MapViewer::window [private]
Reference to the SFML window for rendering.
Definition at line 37 of file MapViewer.hpp.
Referenced by isRunning(), MapViewer(), processEvent(), and render().
wmr
UnicicleWmr MapViewer::wmr [private]
Simulated unicycle WMR (Wheeled Mobile Robot)
Definition at line 47 of file MapViewer.hpp.
Referenced by MapViewer(), render(), and update().
worldXY
sf::Vector2f MapViewer::worldXY [private]
World coordinates (floating point)
Definition at line 53 of file MapViewer.hpp.
The documentation for this class was generated from the following files:
include/artgslam_vsc/MapViewer.hpp
src/MapViewer.cpp