RobotCreator Class Reference
Manages a GUI window for creating and configuring a Unicycle Wheeled Mobile Robot (WMR). Allows user input for robot parameters like width, height, and color, then applies these to the robot model.
#include <RobotCreator.hpp>
Public Member Functions
RobotCreator (UnicicleWmr &wmrRef)
Explicit constructor that requires a reference to the UnicicleWmr instance to configure.
RobotCreator ()=delete
Deleted default constructor to avoid creating an instance without a robot reference.
RobotCreator (const RobotCreator &)=delete
Deleted copy constructor to prevent copying.
RobotCreator & operator= (const RobotCreator &)=delete
Deleted copy assignment operator to prevent copying.
void run ()
Main loop entry point to run the creation window.
void update ()
Updates internal state and GUI elements each frame.
void processEvents ()
Handles user input events like keyboard and mouse.
void render ()
Renders the GUI window and widgets.
void setupWidgets ()
Initializes and sets up all GUI widgets (EditBoxes, Buttons)
void setupCallbacks ()
Connects callbacks for button presses and other GUI events.
bool isRunning () const
Returns true if the creation window is currently open and running.
Private Member Functions
bool isValidFloat (const std::string &str)
Helper function to check if a string represents a valid floating-point number.
bool isValidHexColor (const std::string &str)
Helper function to validate if a string is a valid hexadecimal color code.
sf::Color hexToColor (const std::string &hex)
Converts a hexadecimal color string to an SFML Color object.
Private Attributes
sf::RenderWindow windowRobotCreator
SFML window for robot creation GUI.
tgui::Gui gui
TGUI GUI manager attached to the window.
UnicicleWmr & wmr
Reference to the robot being configured.
tgui::EditBox::Ptr widthBox
GUI widgets for robot parameters input.
tgui::EditBox::Ptr heightBox
Input for robot height.
tgui::EditBox::Ptr colorBox
Input for robot color (hexadecimal string)
tgui::Button::Ptr resetButton
Buttons for user actions.
tgui::Button::Ptr createButton
Applies parameters and creates/configures the robot.
Detailed Description
Manages a GUI window for creating and configuring a Unicycle Wheeled Mobile Robot (WMR). Allows user input for robot parameters like width, height, and color, then applies these to the robot model.
Definition at line 19 of file RobotCreator.hpp.
Constructor & Destructor Documentation
RobotCreator() [1/3]
RobotCreator::RobotCreator (UnicicleWmr & wmrRef) [explicit]
Explicit constructor that requires a reference to the UnicicleWmr instance to configure.
Constructor for RobotCreator.
The explicit keyword prevents unintended implicit conversions.
Parameters
wmrRef Reference to the wheeled mobile robot instance
Loads the GUI form, initializes the window and widgets, and sets up callbacks.
Parameters
wmrRef Reference to the UnicicleWmr robot model to configure.
< Link widget variables to GUI elements
< Setup button callbacks
Definition at line 13 of file RobotCreator.cpp.
    : windowRobotCreator(sf::VideoMode(400, 250), "Robot Creator"),
      gui(windowRobotCreator), wmr(wmrRef)
{
    // Load form file path from ROS package
    std::string package_path = ros::package::getPath("artgslam_vsc");
    std::string formPath = package_path + "/assets/forms/createRobot.txt";
    try {
        gui.loadWidgetsFromFile(formPath);
    } catch (const tgui::Exception& e) {
        std::cerr << "Error loading GUI form: " << e.what() << std::endl;
    }
    setupWidgets(); /**< Link widget variables to GUI elements */
    setupCallbacks(); /**< Setup button callbacks */
}
References gui, setupCallbacks(), and setupWidgets().
RobotCreator() [2/3]
RobotCreator::RobotCreator () [delete]
Deleted default constructor to avoid creating an instance without a robot reference.
RobotCreator() [3/3]
RobotCreator::RobotCreator (const RobotCreator &) [delete]
Deleted copy constructor to prevent copying.
Member Function Documentation
hexToColor()
sf::Color RobotCreator::hexToColor (const std::string & hex) [private]
Converts a hexadecimal color string to an SFML Color object.
Converts a hex color string to an SFML color object.
Assumes valid input format.
Parameters
hex Hexadecimal color string
Returns
Corresponding sf::Color
Supports both 3-digit (#abc) and 6-digit (#aabbcc) hex formats.
Parameters
hex The hex color string.
Returns
Corresponding sf::Color object.
Definition at line 209 of file RobotCreator.cpp.
{
    std::string h = hex;
    if (h.empty()) return sf::Color::White;
    if (h[0] == '#') h = h.substr(1);
    if (h.length() == 3)
    {
        h = {h[0], h[0], h[1], h[1], h[2], h[2]};
    }
    unsigned int r = std::stoul(h.substr(0, 2), nullptr, 16);
    unsigned int g = std::stoul(h.substr(2, 2), nullptr, 16);
    unsigned int b = std::stoul(h.substr(4, 2), nullptr, 16);
    return sf::Color(r, g, b);
}
Referenced by setupCallbacks().
isRunning()
bool RobotCreator::isRunning () const
Returns true if the creation window is currently open and running.
Checks if the window is still open.
Returns
true if the window is open, false otherwise.
Definition at line 170 of file RobotCreator.cpp.
{
    return windowRobotCreator.isOpen();
}
References windowRobotCreator.
Referenced by run().
isValidFloat()
bool RobotCreator::isValidFloat (const std::string & str) [private]
Helper function to check if a string represents a valid floating-point number.
Validates if a string represents a valid floating point number.
Parameters
str Input string
Returns
true if valid float, false otherwise
Parameters
str The string to validate.
Returns
true if valid float format, false otherwise.
Definition at line 181 of file RobotCreator.cpp.
{
    if (str.empty()) return false;
    static const std::regex floatRegex(R"(^-?\d+(\.\d+)?$)");
    return std::regex_match(str, floatRegex);
}
Referenced by setupCallbacks().
isValidHexColor()
bool RobotCreator::isValidHexColor (const std::string & str) [private]
Helper function to validate if a string is a valid hexadecimal color code.
Validates if a string is a valid hex color (#RGB or #RRGGBB).
Supports formats like `#RRGGBB` or `RRGGBB`.
Parameters
str Input string
Returns
true if valid hex color, false otherwise
Parameters
str The hex color string.
Returns
true if valid hex color format, false otherwise.
Definition at line 194 of file RobotCreator.cpp.
{
    static const std::regex hexShort(R"(#([A-Fa-f0-9]{3}))");
    static const std::regex hexLong(R"(#([A-Fa-f0-9]{6}))");
    return std::regex_match(str, hexShort) || std::regex_match(str, hexLong);
}
Referenced by setupCallbacks().
operator=()
RobotCreator& RobotCreator::operator= (const RobotCreator &) [delete]
Deleted copy assignment operator to prevent copying.
processEvents()
void RobotCreator::processEvents ()
Handles user input events like keyboard and mouse.
Processes all window events.
Polls and handles SFML window events and delegates event handling to TGUI.
Definition at line 51 of file RobotCreator.cpp.
{
    sf::Event event;
    while (windowRobotCreator.pollEvent(event))
    {
        gui.handleEvent(event);
        if (event.type == sf::Event::Closed)
            windowRobotCreator.close();
    }
}
References gui, and windowRobotCreator.
Referenced by run().
render()
void RobotCreator::render ()
Renders the GUI window and widgets.
Clears the window and draws the GUI.
Definition at line 74 of file RobotCreator.cpp.
{
    windowRobotCreator.clear(sf::Color::White);
    gui.draw();
    windowRobotCreator.display();
}
References gui, and windowRobotCreator.
Referenced by run().
run()
void RobotCreator::run ()
Main loop entry point to run the creation window.
Runs the main loop of the Robot Creator window.
Processes events, updates state, and renders GUI until the window is closed. < Handle input and window events
< Update logic (currently unused)
< Render the GUI
Definition at line 36 of file RobotCreator.cpp.
{
    while (isRunning())
    {
        processEvents(); /**< Handle input and window events */
        update(); /**< Update logic (currently unused) */
        render(); /**< Render the GUI */
    }
}
References isRunning(), processEvents(), render(), and update().
Referenced by MapViewer::MapViewer().
setupCallbacks()
void RobotCreator::setupCallbacks ()
Connects callbacks for button presses and other GUI events.
Sets up callbacks for reset and create buttons.
Resets all input fields on reset button press.
Validates input and creates robot on create button press.
Definition at line 110 of file RobotCreator.cpp.
{
    if (!resetButton || !createButton) return;
    resetButton->onPress([this]() {
        widthBox->setText("");
        heightBox->setText("");
        colorBox->setText("");
    });
    createButton->onPress([this]() {
        std::string widthStr = widthBox->getText().toStdString();
        std::string heightStr = heightBox->getText().toStdString();
        std::string colorStr = colorBox->getText().toStdString();
        bool valid = true;
        if (!isValidFloat(widthStr)) {
            widthBox->setText("");
            valid = false;
        }
        if (!isValidFloat(heightStr)) {
            heightBox->setText("");
            valid = false;
        }
        if (!isValidHexColor(colorStr)) {
            colorBox->setText("");
            valid = false;
        }
        if (!valid) {
            std::cout << "Error: Invalid input. Please check the fields.\n";
            return;
        }
        float width = std::stof(widthStr);
        float height = std::stof(heightStr);
        sf::Color color = hexToColor(colorStr);
        wmr.setDimensions(width, height);
        wmr.setColor(color);
        wmr.setRobotActive(true);
        std::cout << "Robot created:\n";
        std::cout << "Width: " << width << ", Height: " << height << "\n";
        std::cout << "Color RGB: ("
                  << static_cast<int>(color.r) << ", "
                  << static_cast<int>(color.g) << ", "
                  << static_cast<int>(color.b) << ")\n";
        windowRobotCreator.close();
    });
}
References colorBox, createButton, heightBox, hexToColor(), isValidFloat(), isValidHexColor(), resetButton, UnicicleWmr::setColor(), UnicicleWmr::setDimensions(), UnicicleWmr::setRobotActive(), widthBox, windowRobotCreator, and wmr.
Referenced by RobotCreator().
setupWidgets()
void RobotCreator::setupWidgets ()
Initializes and sets up all GUI widgets (EditBoxes, Buttons)
Retrieves and validates GUI widgets from the loaded form.
Definition at line 84 of file RobotCreator.cpp.
{
    widthBox = gui.get<tgui::EditBox>("widthBox");
    heightBox = gui.get<tgui::EditBox>("heightBox");
    colorBox = gui.get<tgui::EditBox>("colorBox");
    resetButton = gui.get<tgui::Button>("Button1");
    createButton = gui.get<tgui::Button>("Button2");
    if (!widthBox || !heightBox || !colorBox || !resetButton || !createButton)
    {
        std::cerr << "[ERROR] One or more widgets could not be found.\n";
        return;
    }
    // Optional: set input validators (commented out)
    // widthBox->setInputValidator(R"(^-?\d*\.?\d+$)");
    // heightBox->setInputValidator(R"(^-?\d*\.?\d+$)");
}
References colorBox, createButton, gui, heightBox, resetButton, and widthBox.
Referenced by RobotCreator().
update()
void RobotCreator::update ()
Updates internal state and GUI elements each frame.
Placeholder for future update logic.
Definition at line 66 of file RobotCreator.cpp.
{
    // Currently no update logic
}
Referenced by run().
Member Data Documentation
colorBox
tgui::EditBox::Ptr RobotCreator::colorBox [private]
Input for robot color (hexadecimal string)
Definition at line 67 of file RobotCreator.hpp.
Referenced by setupCallbacks(), and setupWidgets().
createButton
tgui::Button::Ptr RobotCreator::createButton [private]
Applies parameters and creates/configures the robot.
Definition at line 71 of file RobotCreator.hpp.
Referenced by setupCallbacks(), and setupWidgets().
gui
tgui::Gui RobotCreator::gui [private]
TGUI GUI manager attached to the window.
Definition at line 61 of file RobotCreator.hpp.
Referenced by processEvents(), render(), RobotCreator(), and setupWidgets().
heightBox
tgui::EditBox::Ptr RobotCreator::heightBox [private]
Input for robot height.
Definition at line 66 of file RobotCreator.hpp.
Referenced by setupCallbacks(), and setupWidgets().
resetButton
tgui::Button::Ptr RobotCreator::resetButton [private]
Buttons for user actions.
Resets all input fields to default
Definition at line 70 of file RobotCreator.hpp.
Referenced by setupCallbacks(), and setupWidgets().
widthBox
tgui::EditBox::Ptr RobotCreator::widthBox [private]
GUI widgets for robot parameters input.
Input for robot width
Definition at line 65 of file RobotCreator.hpp.
Referenced by setupCallbacks(), and setupWidgets().
windowRobotCreator
sf::RenderWindow RobotCreator::windowRobotCreator [private]
SFML window for robot creation GUI.
Definition at line 60 of file RobotCreator.hpp.
Referenced by isRunning(), processEvents(), render(), and setupCallbacks().
wmr
UnicicleWmr& RobotCreator::wmr [private]
Reference to the robot being configured.
Definition at line 62 of file RobotCreator.hpp.
Referenced by setupCallbacks().
The documentation for this class was generated from the following files:
include/artgslam_vsc/RobotCreator.hpp
src/RobotCreator.cpp