FileManager Class Reference
Manages file input/output operations for grid map visualization.
#include <FileManager.hpp>
Public Member Functions
FileManager (GridMap &mapRef, LiveMap &lmapRef)
Constructor.
void loadDialog ()
Opens a file dialog to select a file and loads its data into the map.
void saveDialog ()
Opens a file dialog to save the current data (coordinates).
void dataLoad (const std::string &filename, std::vector< double > &x, std::vector< double > &y)
Loads coordinate data from a file into x and y vectors.
void saveData (const std::string &filename, std::vector< double > &x, std::vector< double > &y)
Saves x and y coordinate data to a file.
void saveScreen (const std::string &filename)
Saves a screenshot of the current visualization to an image file.
Private Attributes
GridMap & map
Reference to the grid map object.
LiveMap & lmap
std::string loadedFilename
Path of the last loaded or saved file.
Detailed Description
Manages file input/output operations for grid map visualization.
This class handles loading data from files to populate the map, saving coordinate data, and exporting screenshots.
Definition at line 33 of file FileManager.hpp.
Constructor & Destructor Documentation
FileManager()
FileManager::FileManager (GridMap & mapRef, LiveMap & lmapRef)
Constructor.
Constructor that stores a reference to the GridMap instance for interaction.
Parameters
mapRef Reference to the GridMap to work with
mapRef Reference to the GridMap.
Definition at line 21 of file FileManager.cpp.
    : map(mapRef),lmap(lmapRef)
{
}
Member Function Documentation
dataLoad()
void FileManager::dataLoad (const std::string & filename, std::vector< double > & x, std::vector< double > & y)
Loads coordinate data from a file into x and y vectors.
Loads (x,y) data points from a CSV file into the provided vectors.
Parameters
filename Path of the file to read from
x Output vector of x coordinates
y Output vector of y coordinates
filename Path to the CSV file.
x Output vector for x coordinates.
y Output vector for y coordinates.
Definition at line 101 of file FileManager.cpp.
{
    x.clear();
    y.clear();
    std::ifstream file(filename);
    if (!file.is_open()) {
        std::cerr << "Error opening file: " << filename << std::endl;
        return;
    }
    std::string line;
    size_t count = 0;
    // Read file line by line
    while (std::getline(file, line)) {
        std::stringstream ss(line);
        std::string token;
        std::vector<std::string> tokens;
        // Tokenize by commas
        while (std::getline(ss, token, ',')) {
            tokens.push_back(token);
        }
        if (tokens.size() >= 2) {
            try {
                double xVal, yVal;
                // Support CSV files with two or more columns
                if (tokens.size() == 2) {
                    // Format: x,y
                    xVal = std::stod(tokens[0]);
                    yVal = std::stod(tokens[1]);
                } else {
                    // Format: skip first column, use second and third columns as x,y
                    xVal = std::stod(tokens[1]);
                    yVal = std::stod(tokens[2]);
                }
                x.push_back(xVal);
                y.push_back(yVal);
                ++count;
            } catch (const std::exception& e) {
                std::cerr << "Error parsing line: " << line << " (" << e.what() << ")\n";
            }
        } else {
            std::cerr << "Invalid line format (less than 2 columns): " << line << "\n";
        }
    }
    std::cout << "Loaded " << count << " points\n";
}
Referenced by loadDialog().
loadDialog()
void FileManager::loadDialog ()
Opens a file dialog to select a file and loads its data into the map.
Opens a file dialog to select a CSV dataset file, loads the data, and updates the map accordingly.
Definition at line 30 of file FileManager.cpp.
{
    const char* path = tinyfd_openFileDialog(
        "Open Dataset", // Dialog title
        "", // Default path
        0, // Number of filters (0 = none)
        nullptr, // Filter patterns (ignored when count=0)
        nullptr, // Filter description
        0 // Allow multiple selection? (0 = no)
    );
    if (path) {
        std::cout << "Selected file: " << path << std::endl;
        loadedFilename = path;
        // Load CSV data into vectors
        std::vector<double> xData, yData;
        dataLoad(loadedFilename, xData, yData);
        // Update map points with loaded real-world coordinates
        map.setPoints(xData, yData);
        // Convert real-world coordinates to grid indices and fill the occupancy grid
        std::vector<int> xGrid, yGrid;
        map.xy2Grid(map.getRealX(), map.getRealY(), xGrid, yGrid);
        map.fillGrid(xGrid, yGrid);
    } else {
        std::cout << "No file was selected.\n";
    }
}
References dataLoad(), GridMap::fillGrid(), GridMap::getRealX(), GridMap::getRealY(), loadedFilename, map, GridMap::setPoints(), tinyfd_openFileDialog(), and GridMap::xy2Grid().
Referenced by MapViewer::MapViewer().
saveData()
void FileManager::saveData (const std::string & filename, std::vector< double > & x, std::vector< double > & y)
Saves x and y coordinate data to a file.
Saves vectors of x and y coordinates to a CSV file.
Parameters
filename Path of the file to write to
x Vector of x coordinates
y Vector of y coordinates
filename Path to the output file.
x Vector of x coordinates.
y Vector of y coordinates.
Definition at line 161 of file FileManager.cpp.
{
    if (x.size() != y.size()) {
        std::cerr << "Error: x and y vector sizes do not match.\n";
        return;
    }
    std::ofstream outFile(filename);
    if (!outFile) {
        std::cerr << "Error: Cannot open file for writing.\n";
        return;
    }
    // Use high precision for floating point output
    outFile << std::fixed << std::setprecision(17);
    for (size_t i = 0; i < x.size(); ++i) {
        outFile << x[i] << "," << y[i] << "\n";
    }
    outFile.close();
    std::cout << "Text file saved successfully.\n";
}
Referenced by saveDialog().
saveDialog()
void FileManager::saveDialog ()
Opens a file dialog to save the current data (coordinates).
Opens a save file dialog and saves current real-world map data to a CSV file.
Definition at line 64 of file FileManager.cpp.
{
    const char* path = tinyfd_saveFileDialog(
        "Save File", // Dialog title
        "output.txt", // Default filename
        0, // Number of filters (0 = none)
        nullptr, // Filter patterns
        nullptr // Filter description
    );
    if (path) {
        std::cout << "Saving to: " << path << std::endl;
        // Save the real-world coordinates to the file
        if(lmap.getIsActive()==false){
        
        saveData(path,
                 const_cast<std::vector<double>&>(map.getRealX()),
                 const_cast<std::vector<double>&>(map.getRealY()));
        }
        else{
            saveData(path,
                 const_cast<std::vector<double>&>(lmap.getRealX()),
                 const_cast<std::vector<double>&>(lmap.getRealY()));
        }
    } else {
        std::cout << "Save operation was canceled.\n";
    }
}
References LiveMap::getIsActive(), GridMap::getRealX(), LiveMap::getRealX(), GridMap::getRealY(), LiveMap::getRealY(), lmap, map, saveData(), and tinyfd_saveFileDialog().
Referenced by MapViewer::MapViewer().
saveScreen()
void FileManager::saveScreen (const std::string & filename)
Saves a screenshot of the current visualization to an image file.
Placeholder for saving a screenshot of the map window.
Parameters
filename Path of the image file to create
filename Suggested filename for saving.
Note: Implementation to capture and save SFML window content is pending.
Definition at line 190 of file FileManager.cpp.
{
    const char* path = tinyfd_saveFileDialog(
        "Save Image",
        "Map.png",
        0,
        nullptr,
        nullptr
    );
    if (path) {
        // TODO: Implement screenshot capture and saving using SFML RenderWindow
        return;
    }
}
References tinyfd_saveFileDialog().
Member Data Documentation
lmap
LiveMap& FileManager::lmap [private]
Definition at line 37 of file FileManager.hpp.
Referenced by saveDialog().
loadedFilename
std::string FileManager::loadedFilename [private]
Path of the last loaded or saved file.
Definition at line 38 of file FileManager.hpp.
Referenced by loadDialog().
map
GridMap& FileManager::map [private]
Reference to the grid map object.
Definition at line 36 of file FileManager.hpp.
Referenced by loadDialog(), and saveDialog().
The documentation for this class was generated from the following files:
include/artgslam_vsc/FileManager.hpp
src/FileManager.cpp