MenuBar Class Reference
Manages the menu bar located at the bottom of the screen. Provides options for file handling, view controls, robot creation, and live mode toggle.
#include <MenuBar.hpp>
Public Member Functions
MenuBar (tgui::Gui &gui)
Constructor: initializes and places the menu elements within the given GUI.
void setCallbacks (std::function< void()> onOpen, std::function< void()> onSave, std::function< void()> onSaveImage, std::function< void()> onClose, std::function< void()> onResetView, std::function< void()> onClearView, std::function< void()> onCreateRobot, std::function< void()> onSimulation)
Sets the callback functions for each menu option:
void updateCoordinates (const std::string &text)
Updates the label showing the current grid coordinates of the mouse.
bool getLiveMode () const
Returns whether live mode is currently enabled.
Private Member Functions
void setupMenu (tgui::Gui &gui)
Helper to set up the main menu bar structure and entries.
void setupCordLable (tgui::Gui &gui)
Helper to set up the label that shows mouse grid coordinates.
void setupliveToggle (tgui::Gui &gui)
Helper to set up the toggle button for live mode (ROS streaming).
Private Attributes
tgui::MenuBar::Ptr menuBar
Pointer to the TGUI MenuBar widget.
tgui::Label::Ptr coordLabel
Label to show mouse position in grid coordinates.
tgui::ToggleButton::Ptr liveToggle
Toggle button to activate/deactivate live mode.
bool liveMode = false
Indicates whether live mode is active.
Detailed Description
Manages the menu bar located at the bottom of the screen. Provides options for file handling, view controls, robot creation, and live mode toggle.
Definition at line 14 of file MenuBar.hpp.
Constructor & Destructor Documentation
MenuBar()
MenuBar::MenuBar (tgui::Gui & gui)
Constructor: initializes and places the menu elements within the given GUI.
Constructs the MenuBar and initializes all components.
Parameters
gui Reference to the TGUI GUI object where menu elements will be placed.
Creates the main menu bar, the coordinate label, and the live mode toggle button.
Parameters
gui Reference to the TGUI GUI instance where widgets will be added.
< Create the main menu bar
< Create coordinate display label
< Create toggle button for live mode
Definition at line 14 of file MenuBar.cpp.
                             {
    setupMenu(gui); /**< Create the main menu bar */
    setupCordLable(gui); /**< Create coordinate display label */
    setupliveToggle(gui); /**< Create toggle button for live mode */
}
References setupCordLable(), setupliveToggle(), and setupMenu().
Member Function Documentation
getLiveMode()
bool MenuBar::getLiveMode () const [inline]
Returns whether live mode is currently enabled.
Returns
true if live mode is active, false otherwise.
Definition at line 63 of file MenuBar.hpp.
{ return liveMode; };
References liveMode.
Referenced by MapViewer::render(), and MapViewer::update().
setCallbacks()
void MenuBar::setCallbacks (std::function< void()> onOpen, std::function< void()> onSave, std::function< void()> onSaveImage, std::function< void()> onClose, std::function< void()> onResetView, std::function< void()> onClearView, std::function< void()> onCreateRobot, std::function< void()> onSimulation)
Sets the callback functions for each menu option:
Connects external callback functions to the menu items.
onOpen: Open a map file
onSave: Save current map state
onSaveImage: Export current map as an image
onClose: Exit or close the application
onResetView: Reset camera view
onClearView: Clear the current grid/map
onCreateRobot: Trigger robot creation interface
onSimulation: Start or stop the simulation
Parameters
onOpen Callback for `Open` menu option
onSave Callback for `Save` menu option
onSaveImage Callback for `Save Image` menu option
onClose Callback for `Close` menu option
onResetView Callback for `Reset View` menu option
onClearView Callback for `Clear View` menu option
onCreateRobot Callback for `Create Robot` menu option
onSimulation Callback for `Simulation` menu option
Allows external code to respond to menu item selections.
Parameters
onOpen Callback invoked when `Open` is selected.
onSave Callback invoked when `Save` is selected.
onSaveImage Callback invoked when `Save2Image` is selected.
onClose Callback invoked when `Close` is selected.
onResetView Callback invoked when `ResetView` is selected.
onClearView Callback invoked when `ClearView` is selected.
onCreateRobot Callback invoked when `WMR` is selected under `Create object`.
onSimulation Callback invoked when `A*` is selected under `Simulation`.
Definition at line 133 of file MenuBar.cpp.
{
    menuBar->connectMenuItem("File", "Open", [onOpen]() {
        if (onOpen) onOpen();
    });
    menuBar->connectMenuItem("File", "Save", [onSave]() {
        if (onSave) onSave();
    });
    menuBar->connectMenuItem("File", "Save2Image", [onSaveImage]() {
        if (onSaveImage) onSaveImage();
    });
    menuBar->connectMenuItem("File", "Close", [onClose]() {
        if (onClose) onClose();
    });
    menuBar->connectMenuItem("View", "ResetView", [onResetView]() {
        if (onResetView) onResetView();
    });
    menuBar->connectMenuItem("View", "ClearView", [onClearView]() {
        if (onClearView) onClearView();
    });
    menuBar->connectMenuItem("Create object", "WMR", [onCreateRobot]() {
        if (onCreateRobot) onCreateRobot();
    });
    menuBar->connectMenuItem("Simulation", "A*", [onSimulation]() {
        if (onSimulation) onSimulation();
    });
}
References menuBar.
Referenced by MapViewer::MapViewer().
setupCordLable()
void MenuBar::setupCordLable (tgui::Gui & gui) [private]
Helper to set up the label that shows mouse grid coordinates.
Sets up the coordinate label displayed at the bottom right of the window.
Parameters
gui Reference to the TGUI GUI object.
The label initially shows placeholder text and has transparent background with black text.
Parameters
gui Reference to the TGUI GUI instance.
Definition at line 63 of file MenuBar.cpp.
                                         {
    coordLabel = tgui::Label::create("Grid: -, Real: -");
    coordLabel->setTextSize(14);
    coordLabel->setPosition("100% - 400", "100% - 20"); // Bottom right, offset leftwards
    coordLabel->getRenderer()->setBackgroundColor(tgui::Color::Transparent);
    coordLabel->getRenderer()->setTextColor(tgui::Color::Black);
    gui.add(coordLabel, "CoordLabel");
}
References coordLabel.
Referenced by MenuBar().
setupliveToggle()
void MenuBar::setupliveToggle (tgui::Gui & gui) [private]
Helper to set up the toggle button for live mode (ROS streaming).
Creates and configures the live mode toggle button.
Parameters
gui Reference to the TGUI GUI object.
The button switches between ON/OFF states with color feedback (green/red). Positioned near the coordinate label.
Parameters
gui Reference to the TGUI GUI instance.
Definition at line 80 of file MenuBar.cpp.
                                          {
    liveToggle = tgui::ToggleButton::create();
    liveToggle->setSize(50, 20);
    liveToggle->setText("Live");
    liveToggle->setPosition("100% - 60", "100% - 20");
    auto renderer = liveToggle->getRenderer();
    renderer->setRoundedBorderRadius(10);
    renderer->setTextColor(tgui::Color::White);
    renderer->setBorderColor(tgui::Color::White);
    // Default OFF (red) colors
    renderer->setBackgroundColor(tgui::Color(120, 0, 0));
    renderer->setBackgroundColorHover(tgui::Color(180, 60, 60));
    renderer->setBackgroundColorDown(tgui::Color(255, 100, 100));
    gui.add(liveToggle);
    liveMode = false;
    // Change toggle button color based on state (green for ON, red for OFF)
    liveToggle->onToggle([this](bool state) {
        liveMode = state;
        auto renderer = liveToggle->getRenderer();
        if (state) {
            // ON state colors (green)
            renderer->setBackgroundColor(tgui::Color(0, 180, 0));
            renderer->setBackgroundColorHover(tgui::Color(80, 220, 80));
            renderer->setBackgroundColorDown(tgui::Color(100, 255, 100));
        } else {
            // OFF state colors (red)
            renderer->setBackgroundColor(tgui::Color(120, 0, 0));
            renderer->setBackgroundColorHover(tgui::Color(180, 60, 60));
            renderer->setBackgroundColorDown(tgui::Color(255, 100, 100));
        }
    });
}
References liveMode, and liveToggle.
Referenced by MenuBar().
setupMenu()
void MenuBar::setupMenu (tgui::Gui & gui) [private]
Helper to set up the main menu bar structure and entries.
Creates and configures the main menu bar with categorized menu items.
Parameters
gui Reference to the TGUI GUI object.
The menu includes File, View, Create Object, and Simulation categories with their items. The menu bar is positioned at the bottom and menus open upward.
Parameters
gui Reference to the TGUI GUI instance.
Definition at line 28 of file MenuBar.cpp.
                                    {
    menuBar = tgui::MenuBar::create();
    menuBar->setSize("100%", 20);
    menuBar->setPosition(0, "100% - 20"); // Bottom of the window
    menuBar->setInvertedMenuDirection(true); // Menus open upward
    gui.add(menuBar);
    // File menu and items
    menuBar->addMenu("File");
    menuBar->addMenuItem("File", "Open");
    menuBar->addMenuItem("File", "Save");
    menuBar->addMenuItem("File", "Save2Image");
    menuBar->addMenuItem("File", "Close");
    // View menu and items
    menuBar->addMenu("View");
    menuBar->addMenuItem("View", "ResetView");
    menuBar->addMenuItem("View", "ClearView");
    // Create object menu and items
    menuBar->addMenu("Create object");
    menuBar->addMenuItem("Create object", "WMR");
    // Simulation menu and items
    menuBar->addMenu("Simulation");
    menuBar->addMenuItem("Simulation", "A*");
}
References menuBar.
Referenced by MenuBar().
updateCoordinates()
void MenuBar::updateCoordinates (const std::string & text)
Updates the label showing the current grid coordinates of the mouse.
Updates the coordinate label text.
Parameters
text The text to display (usually formatted coordinates)
text New coordinate string to display.
Definition at line 181 of file MenuBar.cpp.
                                                     {
    if (coordLabel)
        coordLabel->setText(text);
}
References coordLabel.
Referenced by MapViewer::update().
Member Data Documentation
coordLabel
tgui::Label::Ptr MenuBar::coordLabel [private]
Label to show mouse position in grid coordinates.
Definition at line 85 of file MenuBar.hpp.
Referenced by setupCordLable(), and updateCoordinates().
liveMode
bool MenuBar::liveMode = false [private]
Indicates whether live mode is active.
Definition at line 88 of file MenuBar.hpp.
Referenced by getLiveMode(), and setupliveToggle().
liveToggle
tgui::ToggleButton::Ptr MenuBar::liveToggle [private]
Toggle button to activate/deactivate live mode.
Definition at line 86 of file MenuBar.hpp.
Referenced by setupliveToggle().
menuBar
tgui::MenuBar::Ptr MenuBar::menuBar [private]
Pointer to the TGUI MenuBar widget.
Definition at line 84 of file MenuBar.hpp.
Referenced by setCallbacks(), and setupMenu().
The documentation for this class was generated from the following files:
include/artgslam_vsc/MenuBar.hpp
src/MenuBar.cpp