GridMap Class Reference
Handles the creation and management of map data.
#include <GridMap.hpp>
Public Member Functions
GridMap (int size, double resolution, ViewController &controller)
Constructor.
const std::vector< double > & getRealX () const
Getters for real-world x coordinates.
const std::vector< double > & getRealY () const
Getters for real-world y coordinates.
int getCellIndexX (double realX) const
Convert a real-world x coordinate to grid index.
int getCellIndexY (double realY) const
Convert a real-world y coordinate to grid index.
void addPoints (double x, double y)
Add a point to the grid.
void setPoints (const std::vector< double > &newX, const std::vector< double > &newY)
Replace all current points with new ones.
void clearPoints ()
Clear all stored real-world points.
void setStart (int i, int j)
Set the start point in the grid (stored as ASCII 's').
void setGoal (int i, int j)
Set the goal point in the grid (stored as ASCII 'g').
int isOccupied (int i, int j) const
Query cell status.
void xy2Grid (const std::vector< double > &x, const std::vector< double > &y, std::vector< int > &xGrid, std::vector< int > &yGrid)
Convert real-world coordinates to grid indices.
void fillGrid (const std::vector< int > &xGrid, const std::vector< int > &yGrid)
Fill the occupancy grid using grid index vectors.
const std::vector< std::vector< int > > & getGrid () const
Get a const reference to the occupancy grid.
void clearGridMap ()
Clear the entire occupancy grid.
void clearSetPoints (sf::Vector2i cellIndex)
Clear start or goal markers from a cell.
void draw (sf::RenderTarget &target, float pixelsPerMeter) const
Draw the map using SFML.
int getMapSize () const
Get the number of cells per side.
Private Attributes
int gridSize
Number of cells in the grid (map size)
double gridResolution
Size of each cell in meters.
std::vector< double > posX
std::vector< double > posY
Real-world coordinates from sonar data.
std::vector< std::vector< int > > grid
2D occupancy grid
ViewController & controller
Reference to view controller (for proper rendering)
Detailed Description
Handles the creation and management of map data.
It stores (x, y) coordinates from sonar readings, converts them into grid cell indices, and fills a 2D occupancy grid.
Definition at line 13 of file GridMap.hpp.
Constructor & Destructor Documentation
GridMap()
GridMap::GridMap (int size, double resolution, ViewController & controller)
Constructor.
Constructs a GridMap with given size, resolution, and stores reference to the controller.
Parameters
size Grid dimension (number of cells per side)
resolution Size of each cell in meters
controller Reference to the ViewController for rendering
size Number of cells per grid side (grid is square).
resolution Size of each cell in meters.
controller Reference to the ViewController managing visualization.
Definition at line 11 of file GridMap.cpp.
    : gridSize(size), gridResolution(resolution), controller(controller)
{
    // Initialize the grid with all cells free (0)
    grid.assign(gridSize, std::vector<int>(gridSize, 0));
}
References grid, and gridSize.
Member Function Documentation
addPoints()
void GridMap::addPoints (double x, double y)
Add a point to the grid.
Adds a single real-world point to internal storage.
Parameters
x Real-world x coordinate
y Real-world y coordinate
x X coordinate in meters.
y Y coordinate in meters.
Definition at line 49 of file GridMap.cpp.
{
    posX.push_back(x);
    posY.push_back(y);
}
References posX, and posY.
clearGridMap()
void GridMap::clearGridMap ()
Clear the entire occupancy grid.
Clears all cells in the grid, setting them to free (0).
Definition at line 189 of file GridMap.cpp.
{
    grid.assign(gridSize, std::vector<int>(gridSize, 0));
}
References grid, and gridSize.
Referenced by MapViewer::MapViewer().
clearPoints()
void GridMap::clearPoints ()
Clear all stored real-world points.
Clears all stored real-world points.
Definition at line 69 of file GridMap.cpp.
{
    posX.clear();
    posY.clear();
}
References posX, and posY.
clearSetPoints()
void GridMap::clearSetPoints (sf::Vector2i cellIndex)
Clear start or goal markers from a cell.
Clears a specific grid cell by setting it free (0).
Parameters
cellIndex Index of the cell to clear
cellIndex Grid cell index to clear.
Definition at line 198 of file GridMap.cpp.
{
    if (cellIndex.x >= 0 && cellIndex.y >= 0 &&
        cellIndex.y < gridSize && cellIndex.x < gridSize) {
        grid[cellIndex.y][cellIndex.x] = 0;
    }
}
References grid, and gridSize.
Referenced by RightClickMapMenu::connectSignals().
draw()
void GridMap::draw (sf::RenderTarget & target, float pixelsPerMeter) const
Draw the map using SFML.
Draws the grid cells with obstacles, start and goal points on an SFML render target.
Only filled cells are rendered.
Parameters
target Render target (usually the SFML window)
pixelsPerMeter Scale factor for drawing
target SFML RenderTarget to draw on.
pixelsPerMeter Scaling factor for rendering.
Definition at line 211 of file GridMap.cpp.
{
    if (grid.empty() || grid[0].empty()) return;
    const int rows = static_cast<int>(grid.size());
    const int cols = static_cast<int>(grid[0].size());
    const float cellSize = gridResolution * pixelsPerMeter;
    // Center the grid rendering around origin (0,0)
    const float offsetX = -(cols / 2.f) * cellSize;
    const float offsetY = -(rows / 2.f) * cellSize;
    sf::RectangleShape cellShape({cellSize, cellSize});
    for (int row = 0; row < rows; ++row)
    {
        for (int col = 0; col < cols; ++col)
        {
            const int val = grid[row][col];
            // Assign colors based on cell value
            if (val == 1)
                cellShape.setFillColor(sf::Color::Yellow); // obstacle
            else if (val == 's')
                cellShape.setFillColor(sf::Color::Red); // start
            else if (val == 'g')
                cellShape.setFillColor(sf::Color::Green); // goal
            else
                continue; // skip free cells
            float x = offsetX + col * cellSize;
            float y = offsetY + row * cellSize;
            cellShape.setPosition(x, y);
            target.draw(cellShape);
        }
    }
}
References grid, and gridResolution.
Referenced by MapViewer::render().
fillGrid()
void GridMap::fillGrid (const std::vector< int > & xGrid, const std::vector< int > & yGrid)
Fill the occupancy grid using grid index vectors.
Fills grid cells with obstacles based on given grid indices.
Parameters
xGrid Vector of x indices
yGrid Vector of y indices
xGrid Vector of grid column indices.
yGrid Vector of grid row indices.
Definition at line 162 of file GridMap.cpp.
{
    // Reset grid to free cells
    grid.assign(gridSize, std::vector<int>(gridSize, 0));
    for (size_t i = 0; i < xGrid.size(); ++i) {
        int x = xGrid[i];
        int y = yGrid[i];
        if (x >= 0 && x < gridSize && y >= 0 && y < gridSize) {
            grid[y][x] = 1; // Mark obstacle
        }
    }
}
References grid, and gridSize.
Referenced by FileManager::loadDialog().
getCellIndexX()
int GridMap::getCellIndexX (double realX) const
Convert a real-world x coordinate to grid index.
Converts real-world X coordinate to grid column index.
Parameters
realX X coordinate in meters
Returns
Corresponding grid index
Parameters
realX X coordinate in meters.
Returns
Grid column index corresponding to realX.
Definition at line 23 of file GridMap.cpp.
{
    double offset = (gridSize * gridResolution) / 2.0; // Centered origin offset
    int j = static_cast<int>(std::floor((realX + offset) / gridResolution));
    j = std::clamp(j, 0, gridSize - 1);
    return j;
}
References gridResolution, and gridSize.
getCellIndexY()
int GridMap::getCellIndexY (double realY) const
Convert a real-world y coordinate to grid index.
Converts real-world Y coordinate to grid row index.
Parameters
realY Y coordinate in meters
Returns
Corresponding grid index
Parameters
realY Y coordinate in meters.
Returns
Grid row index corresponding to realY.
Definition at line 36 of file GridMap.cpp.
{
    double offset = (gridSize * gridResolution) / 2.0; // Centered origin offset
    int i = static_cast<int>(std::floor((realY + offset) / gridResolution));
    i = std::clamp(i, 0, gridSize - 1);
    return i;
}
References gridResolution, and gridSize.
getGrid()
const std::vector< std::vector< int > > & GridMap::getGrid () const
Get a const reference to the occupancy grid.
Returns a const reference to the internal grid representation.
Returns
2D grid of occupancy values
Reference to grid.
Definition at line 181 of file GridMap.cpp.
{
    return grid;
}
References grid.
Referenced by MapViewer::render(), and AStar::updatemap().
getMapSize()
int GridMap::getMapSize () const [inline]
Get the number of cells per side.
Returns
Grid size (width or height)
Definition at line 155 of file GridMap.hpp.
{ return gridSize; }
References gridSize.
Referenced by AStar::AStar(), MapViewer::processEvent(), and MapViewer::update().
getRealX()
const std::vector<double>& GridMap::getRealX () const [inline]
Getters for real-world x coordinates.
Returns
Vector of x coordinates
Definition at line 37 of file GridMap.hpp.
{ return posX; }
References posX.
Referenced by FileManager::loadDialog(), and FileManager::saveDialog().
getRealY()
const std::vector<double>& GridMap::getRealY () const [inline]
Getters for real-world y coordinates.
Returns
Vector of y coordinates
Definition at line 43 of file GridMap.hpp.
{ return posY; }
References posY.
Referenced by FileManager::loadDialog(), and FileManager::saveDialog().
isOccupied()
int GridMap::isOccupied (int i, int j) const
Query cell status.
Checks if a grid cell is occupied or special.
Parameters
i Row index
j Column index
Returns
1 = occupied, 0 = free, ASCII 's' = start, ASCII 'g' = goal
Parameters
i Column index in grid.
j Row index in grid.
Returns
1 if obstacle, 0 if free, 's' for start, 'g' for goal, else 1 (occupied).
Definition at line 113 of file GridMap.cpp.
{
    if (grid[j][i] == 1) {
        return 1; // Obstacle
    }
    if (grid[j][i] == 0) {
        return 0; // Free cell
    }
    if (grid[j][i] == 's') {
        return 's'; // Start
    }
    if (grid[j][i] == 'g') {
        return 'g'; // Goal
    }
    // Default to occupied for unexpected values
    return 1;
}
References grid.
Referenced by AStar::step().
setGoal()
void GridMap::setGoal (int col, int row)
Set the goal point in the grid (stored as ASCII 'g').
Sets the goal point on the grid if the cell is free.
Parameters
i Row index
j Column index
col Column index in grid.
row Row index in grid.
Definition at line 96 of file GridMap.cpp.
{
    std::cout << "[setGoal] col=" << col << " row=" << row << '\n';
    if (grid[row][col] == 0) {
        grid[row][col] = 'g'; // Mark cell as goal using ASCII code
        std::cout << "Goal set: " << grid[row][col] << std::endl;
    } else {
        std::cout << "[setGoal] Cell is occupied." << std::endl;
    }
}
References grid.
Referenced by RightClickMapMenu::connectSignals().
setPoints()
void GridMap::setPoints (const std::vector< double > & newX, const std::vector< double > & newY)
Replace all current points with new ones.
Replaces stored points with new vectors of real-world coordinates.
Parameters
newX New vector of x coordinates
newY New vector of y coordinates
newX Vector of X coordinates.
newY Vector of Y coordinates.
Definition at line 60 of file GridMap.cpp.
{
    posX = newX;
    posY = newY;
}
References posX, and posY.
Referenced by FileManager::loadDialog().
setStart()
void GridMap::setStart (int col, int row)
Set the start point in the grid (stored as ASCII 's').
Sets the start point on the grid if the cell is free.
Parameters
i Row index
j Column index
col Column index in grid.
row Row index in grid.
Definition at line 80 of file GridMap.cpp.
{
    std::cout << "[setStart] col=" << col << " row=" << row << '\n';
    if (grid[row][col] == 0) {
        grid[row][col] = 's'; // Mark cell as start using ASCII code
        std::cout << "Start set: " << grid[row][col] << std::endl;
    } else {
        std::cout << "[setStart] Cell is occupied." << std::endl;
    }
}
References grid.
xy2Grid()
void GridMap::xy2Grid (const std::vector< double > & x, const std::vector< double > & y, std::vector< int > & xGrid, std::vector< int > & yGrid)
Convert real-world coordinates to grid indices.
Converts vectors of real-world coordinates to grid indices.
Parameters
x Input vector of x coordinates
y Input vector of y coordinates
xGrid Output vector of x indices
yGrid Output vector of y indices
x Vector of X coordinates.
y Vector of Y coordinates.
xGrid Output vector of grid column indices.
yGrid Output vector of grid row indices.
Definition at line 138 of file GridMap.cpp.
{
    const int halfGrid = gridSize / 2;
    size_t n = std::min(x.size(), y.size());
    xGrid.resize(n);
    yGrid.resize(n);
    for (size_t i = 0; i < n; ++i) {
        int gx = static_cast<int>(std::round(x[i] / gridResolution));
        int gy = static_cast<int>(std::round(y[i] / gridResolution));
        // Translate to centered origin indices
        xGrid[i] = gx + halfGrid;
        yGrid[i] = gy + halfGrid;
    }
}
References gridResolution, and gridSize.
Referenced by FileManager::loadDialog().
Member Data Documentation
controller
ViewController& GridMap::controller [private]
Reference to view controller (for proper rendering)
Definition at line 21 of file GridMap.hpp.
grid
std::vector<std::vector<int> > GridMap::grid [private]
2D occupancy grid
Definition at line 19 of file GridMap.hpp.
Referenced by clearGridMap(), clearSetPoints(), draw(), fillGrid(), getGrid(), GridMap(), isOccupied(), setGoal(), and setStart().
gridResolution
double GridMap::gridResolution [private]
Size of each cell in meters.
Definition at line 17 of file GridMap.hpp.
Referenced by draw(), getCellIndexX(), getCellIndexY(), and xy2Grid().
gridSize
int GridMap::gridSize [private]
Number of cells in the grid (map size)
Definition at line 16 of file GridMap.hpp.
Referenced by clearGridMap(), clearSetPoints(), fillGrid(), getCellIndexX(), getCellIndexY(), getMapSize(), GridMap(), and xy2Grid().
posX
std::vector<double> GridMap::posX [private]
Definition at line 18 of file GridMap.hpp.
Referenced by addPoints(), clearPoints(), getRealX(), and setPoints().
posY
std::vector<double> GridMap::posY [private]
Real-world coordinates from sonar data.
Definition at line 18 of file GridMap.hpp.
Referenced by addPoints(), clearPoints(), getRealY(), and setPoints().
The documentation for this class was generated from the following files:
include/artgslam_vsc/GridMap.hpp
src/GridMap.cpp